import { User } from "@/types/User";

export const leaderboardUsers: User[] = [
  {
    id: "1",
    username: "Rahul",
    avatar: "🧑",
    xp: 12450,
    level: 18,
    speciesDiscovered: 74,
    streak: 21,
    location: "Ranchi",
  },
  {
    id: "2",
    username: "Manish",
    avatar: "👨",
    xp: 11820,
    level: 17,
    speciesDiscovered: 68,
    streak: 14,
    location: "Jamshedpur",
  },
  {
    id: "3",
    username: "Arjun",
    avatar: "🧑‍🦱",
    xp: 9420,
    level: 15,
    speciesDiscovered: 52,
    streak: 9,
    location: "Kolkata",
  },
  {
    id: "4",
    username: "Aman",
    avatar: "👨‍🦰",
    xp: 8750,
    level: 14,
    speciesDiscovered: 48,
    streak: 7,
    location: "Patna",
  },
  {
    id: "5",
    username: "Priya",
    avatar: "👩",
    xp: 8210,
    level: 13,
    speciesDiscovered: 45,
    streak: 12,
    location: "Ranchi",
  },
  {
    id: "6",
    username: "Sneha",
    avatar: "👩‍🦱",
    xp: 7680,
    level: 12,
    speciesDiscovered: 41,
    streak: 5,
    location: "Jamshedpur",
  },
];